[default]
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
SECRET_KEY = ''
FLASK_RUN_HOST = '0.0.0.0'
FLASK_RUN_PORT = 5000
SCHEDULER_API_ENABLED = true


[database]
driver = "sqlite"
relative_path = ""
